services:
  backend:
    environment:
      SMOKESIGNALS_ENV: development
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      target: dev
    environment:
      SMOKESIGNALS_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
